In [26]:
from google.colab import files
uplaoded=files.upload()

Saving Fertilizer_Prediction.csv to Fertilizer_Prediction.csv

In [27]:
import pandas as pd
fertilizer_data_path ='Fertilizer_Prediction.csv'
fert=pd.read_csv(fertilizer_data_path)

In [28]:
from google.colab import files
uplaoded=files.upload()

Saving Crop_recommendation.csv to Crop_recommendation.csv

In [29]:
import pandas as pd
crop_data_path='Crop_recommendation.csv'
crop = pd.read_csv(crop_data_path)

In [30]:
crop.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [31]:
fert.head()

   Unnamed              Crop   N   P   K   pH
0        0              Rice  80  40  40  5.5
1        1    Jowar(Sorghum)  80  40  40  5.5
2        2       Barley(JAV)  70  40  45  5.5
3        3             Maize  80  40  20  5.5
4        4  Ragi( naachnnii)  50  40  20  5.5

In [37]:
# Function for lowering the cases
def change_case(i):
    i = i.replace(" ", "")
    i = i.lower()
    return i
fert['Crop'] = fert['Crop'].apply(change_case)
crop['label'] = crop['label'].apply(change_case)

In [38]:
crop.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [39]:
crop.tail()

        N   P   K  temperature   humidity        ph    rainfall   label
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

In [40]:
crop_names = crop['label'].unique()
crop_names

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [41]:
fert.head()

              Crop   N   P   K   pH
0             rice  80  40  40  5.5
1   jowar(sorghum)  80  40  40  5.5
2      barley(jav)  70  40  45  5.5
3            maize  80  40  20  5.5
4  ragi(naachnnii)  50  40  20  5.5

In [43]:
crop_names_from_fert = fert['Crop'].unique()
crop_names_from_fert

array(['rice', 'jowar(sorghum)', 'barley(jav)', 'maize',
       'ragi(naachnnii)', 'chickpeas(channa)', 'frenchbeans(farasbi)',
       'favabeans(papdi-val)', 'limabeans(pavta)', 'clusterbeans(gavar)',
       'soyabean', 'blackeyedbeans(chawli)', 'kidneybeans',
       'pigeonpeas(toordal)', 'mothbean(matki)', 'mungbeans', 'greenpeas',
       'horsegram(kulthi)', 'blackgram', 'rapeseed(mohri)',
       'corianderseeds', 'mustardseeds', 'sesameseed', 'cuminseeds',
       'lentils(masoordal)', 'brinjal', 'beetroot', 'bittergourd',
       'bottlegourd', 'capsicum', 'cabbage', 'carrot', 'cauliflower',
       'cucumber', 'corianderleaves', 'curryleaves', 'drumstick?moringa',
       'chili', 'ladyfinger', 'mushroom', 'onion', 'potato', 'pumpkin',
       'radish', 'olive', 'sweetpotato', 'fenugreekleaf(methi)',
       'spinach', 'ridgegourd', 'gooseberry(amla)',
       'jambun(syzygiumcumini)', 'ziziphusmauritiana(bor)',
       'garciniaindica(kokam)', 'tamarind', 'tapioca(suran)', 'garlic',
       'lemon', 'tomato', 'ashgourd', 'pineapple', 'pomegranate',
       'banana', 'mango', 'grapes', 'jackfruit', 'guava', 'watermelon',
       'muskmelon', 'apricot', 'apple', 'chickoo', 'custardapple',
       'dates', 'figs', 'orange', 'papaya', 'aniseed', 'asafoetida',
       'bayleaf', 'blackpepper', 'cardamom', 'cinnamon', 'cloves',
       'jaiphal(nutmeg)', 'ginger', 'turmeric', 'cashewnuts', 'raisins',
       'coconut', 'almondnut', 'arecanut', 'pistachionut', 'lemongrass',
       'cotton', 'jute', 'coffee', 'sunflower'], dtype=object)

In [44]:
for i in crop_names_from_fert:
    print(crop[crop['label'] == i])

     N   P   K  temperature   humidity        ph    rainfall label
0   90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1   85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2   60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3   74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4   78  42  42    20.130175  81.604873  7.628473  262.717340  rice
..  ..  ..  ..          ...        ...       ...         ...   ...
95  88  46  42    22.683191  83.463583  6.604993  194.265172  rice
96  93  47  37    21.533463  82.140041  6.500343  295.924880  rice
97  60  55  45    21.408658  83.329319  5.935745  287.576694  rice
98  78  35  44    26.543481  84.673536  7.072656  183.622266  rice
99  65  37  40    23.359054  83.595123  5.333323  188.413665  rice

[100 rows x 8 columns]
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
      N   P   K  temperature   humidity        ph    rainfall  label
100  71  54  16    22.613600  63.690706  5.749914   87.759539  maize
101  61  44  17    26.100184  71.574769  6.931757  102.266244  maize
102  80  43  16    23.558821  71.593514  6.657965   66.719955  maize
103  73  58  21    19.972160  57.682729  6.596061   60.651715  maize
104  61  38  20    18.478913  62.695039  5.970458   65.438354  maize
..   ..  ..  ..          ...        ...       ...         ...    ...
195  90  57  24    18.928519  72.800861  6.158860   82.341629  maize
196  67  35  22    23.305468  63.246480  6.385684  108.760300  maize
197  60  54  19    18.748267  62.498785  6.417820   70.234016  maize
198  83  58  23    19.742133  59.662631  6.381202   65.508614  maize
199  83  57  19    25.730444  70.747393  6.877869   98.737713  maize

[100 rows x 8 columns]
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
      N   P   K  temperature   humidity        ph    rainfall        label
300  13  60  25    17.136928  20.595417  5.685972  128.256862  kidneybeans
301  25  70  16    19.634743  18.907056  5.759237  106.359818  kidneybeans
302  31  55  22    22.913502  21.339531  5.873172  109.225556  kidneybeans
303  40  64  16    16.433403  24.240459  5.926677  140.371781  kidneybeans
304   2  61  20    22.139747  23.022511  5.955617   76.641283  kidneybeans
..   ..  ..  ..          ...        ...       ...         ...          ...
395  27  65  18    20.109938  23.223238  5.595032   73.363865  kidneybeans
396  30  63  16    23.605066  21.905396  5.525905  100.597873  kidneybeans
397  37  70  25    19.731369  24.894874  5.819404   84.063541  kidneybeans
398  27  63  19    20.934099  21.189301  5.562202  133.191442  kidneybeans
399  22  60  24    18.782263  20.247683  5.630665  104.257072  kidneybeans

[100 rows x 8 columns]
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
      N   P   K  temperature   humidity        ph   rainfall      label
700  56  79  15    29.484400  63.199153  7.454532  71.890907  blackgram
701  25  62  21    26.734340  68.139997  7.040056  67.150964  blackgram
702  42  61  22    26.272744  62.288149  7.418651  70.232076  blackgram
703  42  73  25    34.036792  67.211138  6.501869  73.235736  blackgram
704  44  58  18    28.036441  65.066017  6.814411  72.495077  blackgram
..   ..  ..  ..          ...        ...       ...        ...        ...
795  58  73  16    33.369844  65.677182  6.874142  64.895175  blackgram
796  55  77  22    31.434506  62.993035  7.760618  64.776515  blackgram
797  42  79  23    27.716783  63.291034  6.781842  68.565080  blackgram
798  44  77  21    32.639187  61.300905  7.326980  61.838761  blackgram
799  38  62  25    32.747739  67.779546  7.453975  63.377844  blackgram

[100 rows x 8 columns]
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
      N   P   K  temperature   humidity        ph    rainfall        label
900   2  24  38    24.559816  91.635362  5.922936  111.968462  pomegranate
901   6  18  37    19.656901  89.937010  5.937650  108.045893  pomegranate
902   8  26  36    18.783596  87.402477  6.804781  102.518476  pomegranate
903  37  18  39    24.146963  94.511066  6.424671  110.231663  pomegranate
904   0  27  38    22.445813  89.901470  6.738016  109.390600  pomegranate
..   ..  ..  ..          ...        ...       ...         ...          ...
995  33  23  45    20.002190  85.836182  7.116539  112.337046  pomegranate
996   4  14  41    19.851393  89.807323  6.430163  102.818636  pomegranate
997  13  17  45    21.254336  92.650589  7.159521  106.278467  pomegranate
998  39  24  39    23.653741  93.326575  6.431266  109.807618  pomegranate
999   8  28  37    23.884048  86.206138  6.082572  108.312179  pomegranate

[100 rows x 8 columns]
        N   P   K  temperature   humidity        ph    rainfall   label
1000   91  94  46    29.367924  76.249001  6.149934   92.828409  banana
1001  105  95  50    27.333690  83.676752  5.849076  101.049479  banana
1002  108  92  53    27.400536  82.962213  6.276800  104.937800  banana
1003   86  76  54    29.315908  80.115857  5.926825   90.109781  banana
1004   80  77  49    26.054330  79.396545  5.519088  113.229737  banana
...   ...  ..  ..          ...        ...       ...         ...     ...
1095  108  94  47    27.359116  84.546250  6.387431   90.812505  banana
1096   92  81  52    28.010680  76.528081  5.891414  103.704078  banana
1097  110  71  54    28.672089  82.207936  5.725419   94.379875  banana
1098   82  75  55    27.345851  78.487383  6.281070   92.155243  banana
1099  117  81  53    29.507046  78.205856  5.507642   98.125658  banana

[100 rows x 8 columns]
       N   P   K  temperature   humidity        ph    rainfall  label
1100   2  40  27    29.737700  47.548852  5.954627   90.095869  mango
1101  39  24  31    33.556956  53.729798  4.757115   98.675276  mango
1102  21  26  27    27.003155  47.675254  5.699587   95.851183  mango
1103  25  22  25    33.561502  45.535566  5.977414   95.705259  mango
1104   0  21  32    35.898556  54.259642  6.430139   92.197217  mango
...   ..  ..  ..          ...        ...       ...         ...    ...
1195  19  38  26    31.484517  48.779263  4.525722   93.172220  mango
1196  21  21  30    27.698193  51.415932  5.403908  100.772070  mango
1197  22  18  33    30.412358  52.481006  6.621624   93.923759  mango
1198  31  20  30    32.177520  54.013527  6.207496   91.887661  mango
1199  18  26  31    32.611261  47.749165  5.418475   91.101908  mango

[100 rows x 8 columns]
       N    P    K  temperature   humidity        ph   rainfall   label
1200  24  130  195    29.996772  81.541566  6.112306  67.125345  grapes
1201  13  144  204    30.728040  82.426141  6.092242  68.381355  grapes
1202  22  123  205    32.445778  83.885049  5.896343  68.739325  grapes
1203  36  125  196    37.465668  80.659687  6.155261  66.838723  grapes
1204  24  131  196    22.032962  83.743728  5.732454  65.344408  grapes
...   ..  ...  ...          ...        ...       ...        ...     ...
1295  23  138  200     9.851243  80.226317  5.965379  68.428024  grapes
1296  40  143  201    24.972561  82.728287  6.476758  66.700163  grapes
1297   6  142  202    27.237083  82.945733  6.224543  70.425089  grapes
1298  37  124  195    18.706791  83.479529  6.209928  66.596449  grapes
1299  35  134  204     9.949929  82.551390  5.841138  66.008176  grapes

[100 rows x 8 columns]
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
        N   P   K  temperature   humidity        ph   rainfall       label
1300  119  25  51    26.473302  80.922544  6.283818  53.657426  watermelon
1301  119  19  55    25.187800  83.446217  6.818261  46.874209  watermelon
1302  105  30  50    25.299547  81.775276  6.376201  57.041471  watermelon
1303  114   8  50    24.746313  88.308663  6.581588  57.958261  watermelon
1304   93  22  52    26.587407  81.325632  6.932740  41.875400  watermelon
...   ...  ..  ..          ...        ...       ...        ...         ...
1395   97  12  47    25.287846  89.636679  6.765095  58.286977  watermelon
1396  110   7  45    26.638386  84.695469  6.189214  48.324286  watermelon
1397   96  18  50    25.331045  84.305338  6.904242  41.532187  watermelon
1398   83  23  55    26.897502  83.892415  6.463271  43.971937  watermelon
1399  120  24  47    26.986037  89.413849  6.260839  58.548767  watermelon

[100 rows x 8 columns]
        N   P   K  temperature   humidity        ph   rainfall      label
1400  115  17  55    27.578269  94.118782  6.776533  28.082532  muskmelon
1401  114  27  48    27.820548  93.035552  6.528404  26.324055  muskmelon
1402  101  25  52    29.099104  94.222378  6.750146  22.524973  muskmelon
1403  118  18  52    28.049436  90.831307  6.562833  20.762230  muskmelon
1404   95  26  45    29.916906  94.556956  6.117530  28.160572  muskmelon
...   ...  ..  ..          ...        ...       ...        ...        ...
1495   96  13  55    29.527531  94.574594  6.700338  21.135457  muskmelon
1496   82  26  47    28.504164  93.468065  6.565313  24.200072  muskmelon
1497  106  21  52    28.895786  94.789930  6.286515  23.036250  muskmelon
1498   90  15  52    27.049275  91.382173  6.448062  23.657475  muskmelon
1499  106  16  54    28.960179  91.695322  6.585873  24.745820  muskmelon

[100 rows x 8 columns]
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
       N    P    K  temperature   humidity        ph    rainfall  label
1500  24  128  196    22.750888  90.694892  5.521467  110.431786  apple
1501   7  144  197    23.849401  94.348150  6.133221  114.051249  apple
1502  14  128  205    22.608010  94.589006  6.226290  116.039659  apple
1503   8  120  201    21.186674  91.134357  6.321152  122.233323  apple
1504  20  129  201    23.410447  91.699133  5.587906  116.077793  apple
...   ..  ...  ...          ...        ...       ...         ...    ...
1595  40  120  197    23.805938  92.488795  5.889481  119.633555  apple
1596  25  132  198    22.319441  90.851744  5.732758  100.117344  apple
1597  31  137  196    22.144641  93.825674  6.400321  120.631078  apple
1598  36  144  196    23.651676  94.505288  6.496934  115.361127  apple
1599  10  140  197    22.169395  90.271856  6.229499  124.468311  apple

[100 rows x 8 columns]
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
       N   P   K  temperature   humidity        ph    rainfall   label
1600  22  30  12    15.781442  92.510777  6.354007  119.035002  orange
1601  37   6  13    26.030973  91.508193  7.511755  101.284774  orange
1602  27  13   6    13.360506  91.356082  7.335158  111.226688  orange
1603   7  16   9    18.879577  92.043045  7.813917  114.665951  orange
1604  20   7   9    29.477417  91.578029  7.129137  111.172750  orange
...   ..  ..  ..          ...        ...       ...         ...     ...
1695  27  30   5    32.717485  90.546083  7.656978  113.328978  orange
1696  13   8  12    25.162966  92.547360  7.105905  114.311720  orange
1697   6   7   7    27.681673  94.473169  7.199106  113.999515  orange
1698  40  17  15    21.350934  90.949297  7.871063  107.086209  orange
1699  31  26   9    11.698946  93.256389  7.566166  103.200599  orange

[100 rows x 8 columns]
       N   P   K  temperature   humidity        ph    rainfall   label
1700  61  68  50    35.214628  91.497251  6.793245  243.074507  papaya
1701  58  46  45    42.394134  90.790281  6.576261   88.466075  papaya
1702  45  47  55    38.419163  91.142204  6.751453  119.265388  papaya
1703  39  65  53    35.332949  92.115086  6.560743  235.613359  papaya
1704  31  68  45    42.923253  90.076005  6.938313  196.240824  papaya
...   ..  ..  ..          ...        ...       ...         ...     ...
1795  42  59  55    40.102077  94.351102  6.979102  149.119999  papaya
1796  43  64  47    38.589545  91.580765  6.825665  102.270823  papaya
1797  35  67  49    41.313301  91.150880  6.617067  239.742755  papaya
1798  56  59  55    37.035519  91.794302  6.551893  188.518142  papaya
1799  39  64  53    23.012402  91.073555  6.598860  208.335798  papaya

[100 rows x 8 columns]
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
       N   P   K  temperature   humidity        ph    rainfall    label
1800  18  30  29    26.762749  92.860569  6.420019  224.590366  coconut
1801  37  23  28    25.612944  94.313884  5.740055  224.320676  coconut
1802  13  28  33    28.130115  95.648076  5.686973  151.076190  coconut
1803   2  21  35    25.028872  91.537209  6.293662  179.824894  coconut
1804  10  18  35    27.797977  99.645730  6.381975  181.694228  coconut
...   ..  ..  ..          ...        ...       ...         ...      ...
1895  22   8  33    28.435729  95.884041  5.665785  203.928371  coconut
1896  28  27  32    28.940997  93.001090  5.764615  191.772309  coconut
1897  23  21  26    26.454887  93.450426  5.901496  149.222026  coconut
1898  37   5  34    25.794905  93.841506  5.779033  152.423871  coconut
1899  19  26  29    26.931419  98.803136  5.671549  166.571288  coconut

[100 rows x 8 columns]
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
Empty DataFrame
Columns: [N, P, K, temperature, humidity, ph, rainfall, label]
Index: []
        N   P   K  temperature   humidity        ph   rainfall   label
1900  133  47  24    24.402289  79.197320  7.231325  90.802236  cotton
1901  136  36  20    23.095956  84.862757  6.925412  71.295811  cotton
1902  104  47  18    23.965635  76.976967  7.633437  90.756167  cotton
1903  133  47  23    24.887381  75.621372  6.827355  89.760504  cotton
1904  126  38  23    25.362438  83.632761  6.176716  88.436189  cotton
...   ...  ..  ..          ...        ...       ...        ...     ...

In [45]:
crop['label']

0         rice
1         rice
2         rice
3         rice
4         rice
         ...
2195    coffee
2196    coffee
2197    coffee
2198    coffee
2199    coffee
Name: label, Length: 2200, dtype: object

In [46]:
extract_labels = []
for i in crop_names_from_fert:
    if i in crop_names:
        extract_labels.append(i)

In [47]:
# using extract labesl on crop to get all the data related to those labels
new_crop = pd.DataFrame(columns = crop.columns)
new_fert = pd.DataFrame(columns = fert.columns)

In [48]:
for label in extract_labels:
    new_crop = new_crop.append(crop[crop['label'] == label])

In [49]:
for label in extract_labels:
    new_fert = new_fert.append(fert[fert['Crop'] == label].iloc[0])

In [50]:
new_crop

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[1700 rows x 8 columns]

In [62]:
new_fert

           Crop    N    P    K   pH
0          rice   80   40   40  5.5
3         maize   80   40   20  5.5
12  kidneybeans   20   60   20  5.5
18    blackgram   40   60   20  5.0
60  pomegranate   20   10   40  5.5
61       banana  100   75   50  6.5
62        mango   20   20   30  5.0
63       grapes   20  125  200  4.0
66   watermelon  100   10   50  5.5
67    muskmelon  100   10   50  5.5
69        apple   20  125  200  6.5
74       orange   20   10   10  4.0
75       papaya   50   50   50  6.0
88      coconut   20   10   30  5.0
93       cotton  120   40   20  5.5
94         jute   80   40   40  5.5
95       coffee  100   20   30  5.5

In [65]:
from google.colab import files
new_crop.to_csv('CropData_Processing.csv') 
files.download('CropData_Processing.csv')

In [67]:
from google.colab import files
new_fert.to_csv('FertilizerData_Processing.csv') 
files.download('FertilizerData_Processing.csv')